---
- name: Install docker dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add docker repository
  apt_repository:
    repo: deb [arch=armhf] https://download.docker.com/linux/debian bullseye stable
    state: present

- name: Update package list
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: docker-ce
    state: present

- name: Add orangepiuser to docker group
  user:
    name: orangepiuser
    groups: docker
    append: yes
...
