---
- name: Install Fail2Ban
  apt:
    name: fail2ban
    state: present

- name: Configure Fail2Ban
  template:
    src: fail2ban/jail.local.j2
    dest: /etc/fail2ban/jail.local
  notify: reiniciar fail2ban

- name: Restart Fail2Ban
  meta: flush_handlers
...
